### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by XiaoGeNekidora** [CapitanRetraso/Ultimate-Smasher#5]
It's not a really serious bug, just a mistake.
I just clicked a few buttons **without** opening a file then it crashes.
The detailed error message is shown below:
![image](https://user-images.githubusercontent.com/34835642/52469295-06da4e80-2bc6-11e9-99bd-3cd5984dc7d2.png)

OS is Windows 10(CHN).

**Comment by Ret-HZ** [comment]
Thanks for reporting it!
I located the issue and am making sure this doesn't happen in v2.0
